### ISSUE TITLE
Kešky

### ISSUE THREAD

**Issue by weronicamc** [dobrakmato/weronicamc#1]
### Popis funkce
- uživatel klikne na chestku
- otevře se mu single chestka, tam bude item,nebo kniha - inventář 3x9 ze stejným obsahem jako chestka na kterou klikl
- přidá se mu 1-5[herní měny]
- plugin pošle zprávu do chatu, že našel kešku a že za to dostane 1-5[herní měny]
- při opětovném otevření plugin napíše hráči, že kešku již našel
### Požadavky
- statistiky pro kešky
- přiřadit keškám jejich číselné id
  - id budou jedinečné pro každou kešku, smazáním kešky se smaže její id
- toplist: 
  - formát zobrazení: [pořadí] [jméno] / [početnazelezýchkešek]
- sidebar
- Ked sa hrač pokusi otvoriť kešku, overi sa či ma otvorenu predchadzajucu kešku (Podla ID definovaneho pri vytvarani kešky) a ak nema tak plugin neurobi vôbec nič
- Když bude chtít hráč zničit kešku, otevře se keška.
### Commandy
- Admini:
  - /keska create [herní měna] - vytvoření kešky (kliknutím nebo pohledem kurzoru)
    (pokud není zadaná žádná hodnota id, tak se přiřadí nejbližší větší)
  - /keska edit [on/off]- zapne/vypne edit mód pro editaci kešek (edit mód zakáže interakci s keškou, a normalne otevře chestku)
  - /keska info - vypíše id chestky, na kterou se hráč dívá
  - /keska previousID [<IDUpravovanejKešky>] [<IDPredchadzajucejKešky>] - upravuje id předcházející kešky pro kešku
  - /keska list - seznam vytvořených kešek + stránkování
    - formát zobrazení: [id] [pozice] [svět]
  - /keska stats [id] - 
    - formát zobrazení: [jménohráče] [datumnalezení]
  - /keska count [jméno]
    - formát zobrazení: [početnalezenýchkešek] / [početvšechkešek]
  - /keska remove [id] - smazání kešky
  - /keska remove all - smazání všech kešek
  - /keska remove count [jménohráče] - smaže statistiky nalezených kešek pro jednotlivého hráče
  - /keska remove stats - smaže statistiky nalezených kešek pro všechny hráče
  - /keska reload - reload configu
- Hráči
  - /keska countme - zobrazí hráči počet nalezených kešek
    - formát zobrazení: [početnalezenýchkešek] / [početvšechkešek]
  - /keska toplist
    - formát zobrazení: [pořadí] [jméno] / [početnazelezýchkešek]
  - /keska help - nápověda (alias /keska ?) 
    - formát zobrazení:
      - /keska countme - "Zobrazí počet tvých kešek"
      - /keska toplist - "Zobrazí žebříček nerychlejších hledačů kešek"
  - /keska score - Zobrazí scoreboard s hráči na 30 sekund a poté se scoreboard skryje.
### Permise
- Admini:
  - keska.create
  - keska.edit
  - keska.info
  - keska.previousid
  - keska.list
  - keska.stats
  - keska.count
  - keska.remove
  - keska.removeall
  - keska.remove.count
  - keska.remove.stats
  - keska.reload
- Hráči
  - keska.countme
  - keska.toplist
  - keska.help
  - keska.score
### Lokalizace
- CZ
  - /keska create [herní měna] - "&2Keška byla úspěšně vytvořena."
  - /keska list  - "&2Seznam kešek:"
  - /keska edit on - "&2Editace kešek zapnuta"
  - /keska edit off - "&2Editace kešek vypnuta"
  - /keska info - "&2ID této kešky je [id]"
  - /keska stats [id] - "&2Statistiky kešky [id]
  - /keska count <jméno> - "&2Statistika hráče [jméno]
  - /keska remove [id] - "&2Keška byla úspěšně smazána."
  - /keska remove all - "&2Všechny kešky byly úspšně smazány."
  - /keska reload - "&2Proběhl reload configu."
  - /keska remove count - "&2Data hráče [jméno] byly úspešně smazány."
  - /keska remove stats - "&2Data a statistiky kešek byly úspěšně smazány."
  - /keska countme - "&2Počet tvých nalezených kešek: [početnalezenýchkešek]
  - /keska toplist - "c2Nejlepší hledači kešek:"
  - /keska help - "&2Nápověda."
    - formát viz Commandy - Hráči
- Otevírání kešek:
  - první otevření: "&6Nalezl jsi kešku! Celkem máš [početnalezenýchkešek] / [početvšechkešek]."
  - opakované otevtření: "&6Tuto kešku už jsi nalezl."
  - otevření poslední z všech vytvořených kešek: "&6Hurá! Nalezl jsi poslední kešku!"

**Comment by dobrakmato** [comment]
@weronicamc

> /keska create <[herní měna>] 

Preco je tam argument herna mena? Ako ho mam overit, ci je platny, ked v tom prikaze ten argument nema ziaden vyznam. 

> /keska count
> formát zobrazení: <[početnalezenýchkešek>] / <[početvšechkešek>]

Toto ma vracat pocet chestiek najdenych vsetkymi hracmi / pocet vsetkych rozlicnych chestiek?

A predpokladam, ze vsetky formaty zobrazenia maju byt bez tych vsetkych zatvoriek...

**Comment by weronicamc** [comment]
Herni mena je essentials eco a ten format se zavorkami jsi mel nekde napsany, tak jsem myslela, ze to tak ma byt. A ten count tam ma byt /keska count jmeno . Zobrazi to u jednotliveho hrace tyto udaje: jeho nalezene kesky versus vsechny kesky na serveru. Napr. keska count werca zobrazi 2 nalezene kesky versus vsechny kesky na serveru.

**Comment by dobrakmato** [comment]
Ok. A essentials eco je plugin, nie mena. Stale tomu nerozumiem, nevadi, budem to zatial ignorovat.

**Comment by dobrakmato** [comment]
~~Permissions:~~

~~keska.interact - Overridne "otvorenie chestky kopirovanim inventaru chestky - teda ten, kto permission ma, ten moze interactovat so skutocnym inventarom chestky."~~

Zrusene.

**Comment by weronicamc** [comment]
Updatovaný issue:
- přidané nové požadavky
- přidané nové commandy - keska edit [on/off], keska info
- přidané nové permise - keska.edit, keska.interact, keska.info
- přidané nové lokalizace - /keska edit on, /keska edit off, /keska info

**Comment by weronicamc** [comment]
Updatovaný issue:
- přidaný command - /keska previousID
- přidaná permise - keska.previousid

**Comment by dobrakmato** [comment]
No po tyzdni som sa k tomu konecne dostal a vyzera to tak, ze este stale su v tom zadani problemy:

> /keska remove all - smazání všech kešek

Explicitne NIE JE stanovene ze sa maju zmazat aj zaznamy o najdeni kesky hracmi. Avsak po odstraneni kesky z databazy odkazuju zaznamy na neexistujucu kesku. Mozem tam nechat tuto chybu  intergrity aj napriek tomu, ze to je velmi zla praktika, ale nerucim za to, ze to nebude robit problemy. 

Momentalne tento prikaz zmaze **kesku**  a aj **zaznamy hracov o najdeni kesky**.

> /keska reload - reload configu

Na co ma sluzit tento prikaz? Aky config ma reloadovat? Ziadne konfiguracne udaje to neobsahuje...

> /keska toplist

Je sice pekne ze sa ma vypisat poradie, ale ziadne poradie nie je specifikovane. Ak ma plugin ludi zoradit, musis specifikovat podla coho a ako. 

---

Prikaz `help` som upravil tak, ze som dal do prekladov novy kluc - `help_message` ktorym sa specifikuje prave tato pomocna sprava. Zabranime tym dalsim problemom s formatovanim, ktore je pravdepodobne specifikovane v issue nespravne.

**Comment by weronicamc** [comment]
Ahoj keska toplist melo byt podle pitkese to poradi jako v scoreboardu, proto tam neni. Jinak ma to byt takhle:  prvni bude clovek ktery ma nejvic kesek a bude to zobrazene: jmeno pocet kesek. Kdyz dojde k situaci ze nekdo jako prvni najde vsechny kesky, tak zustane jako prvni a ostatni ktery najdou vsechny kesky se budou radit za nim. Melo by se to definovat tak, ze se odstartuje hraci cas pri nalezeni prvni kesky a tenhle cas se mu stopne ve chvili nalezeni posledni kesky. Jinak zitra rano odjizdim, takze testovat budu moci az pristi tyden v patek vecer nebo sobotu.

**Comment by dobrakmato** [comment]
A ako sa zoradia ti, ktori este nenasli poslednu kesku? Oni nemaju byt v tom zozname `keska toplist` a na scoreboarde?

**Comment by weronicamc** [comment]
Ti ktery jeste nenasli vsechny kesky se budou radit za ty, ktere je uz nasli.  Slo by to tak?

**Comment by dobrakmato** [comment]
Cize na vrchu budu ti co nasli vsetky kesky zoradeni podla trvania najdenia poslednej kesky od najdenia prvej a pod nimy budu v lubovolnom poradi ti, ktori nenasli vsetky kesky?

**Comment by weronicamc** [comment]
Pod nima budou serazeny podle poctu, nejvys ty co nasli nejvic az k poslednim tem co nasli 1 nebo 0

**Comment by weronicamc** [comment]
Spis bych dala od 1

**Comment by dobrakmato** [comment]
A ak maju viaceri rovnaki pocet najdenych kesiek? Maju byt zase nahodne (podla usporiadania v RAM)?

**Comment by weronicamc** [comment]
tak se to bude řadit podle času, za který ten počet kešek našli, ti kdo mají menší čas, budou nahoře, ti kdo větší ti budou pod nima

**Comment by dobrakmato** [comment]
Cize tak ako to hovoril pitkes, nie tak ako ty, spravne?

Najprv sa zoradia do skupin podla poctu najdenych kesiek, potom sa v skupinach zoradia podla casu a nakoniec sa vyberie prvych 10 z celeho zoznamu.

**Comment by weronicamc** [comment]
ano podle pitkese ;)

**Comment by dobrakmato** [comment]
Ok. Vecer sa na to pozriem.

**Comment by dobrakmato** [comment]
Inak neviem ci si si to vsimla, ale odpovedala si iba na jednu z mojich pripomienok.

**Comment by weronicamc** [comment]
S keska help to udělej, tak jak to má být, já nevim jak se dělají pluginy a keska reload být už nemusí, naposledy jsme se shodli s pitkesem, že není potřeba.

**Comment by dobrakmato** [comment]
Ked nepovies **ako presne to chces**, tak to nedokazem spravit **presne tak ako to chces**. Citat myslienky som sa zatial nenaucil. Preto som to dal do tych prekladov.

**Comment by weronicamc** [comment]
Přidána nová funkce scoreboardu - po většinu času je skrytý, příkazem se zobrazí na 30 sekund a pak se znova skryje.

Přidán nový příkaz pro pro zobrazení scoreboardu - /keska score .

**Comment by dobrakmato** [comment]
Vyriesene.
